import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { AggregateMetrics, QueryMetrics } from './scoring.js';

export interface RetrieverReport {
  retriever: string;
  discriminatingMetric: string;
  generatedAt: string;
  embeddingModelId: string;
  perQuery: QueryMetrics[];
  aggregateByK: Record<number, AggregateMetrics>;
  aggregateByTypeByK: Record<number, Record<string, AggregateMetrics>>;
}

/** Gitignored — regenerated by every `pnpm run eval` invocation, never committed. */
export const REPORT_DIR = join(process.cwd(), '.eval-report');

export function writeReport(reports: RetrieverReport[]): void {
  mkdirSync(REPORT_DIR, { recursive: true });
  for (const report of reports) {
    writeFileSync(join(REPORT_DIR, `${report.retriever}.json`), JSON.stringify(report, null, 2));
  }
  writeFileSync(
    join(REPORT_DIR, 'summary.json'),
    JSON.stringify(
      reports.map((r) => ({
        retriever: r.retriever,
        generatedAt: r.generatedAt,
        aggregateByK: r.aggregateByK,
      })),
      null,
      2,
    ),
  );
}
